### ISSUE TITLE
Where to get clickbait17-test and clickbait17-validation

### ISSUE THREAD

**Issue by artmatsak** [clickbait-challenge/albacore#2]
The screenshot in the readme shows the `clickbait17-test` and `clickbait17-validation` directories next to `clickbait17-train-170331` and `clickbait17-validation-170630`. I get the latter two directories when unzipping the Clickbait Challange [dataset files](https://www.clickbait-challenge.org/#data). But where do the first two directories come from please?

**Comment by potthast** [comment]
The training data can be obtained here: https://www.clickbait-challenge.org/#data

All other datasets are kept private so that the competition can continue to run and no one has a chance of reverse-engineering the ground truth. You can simply participate by registering at https://www.clickbait-challenge.org.

**Comment by omidvaramin** [comment]
As it is mentioned in the paper, since the real test data set has not yet been released, I split clickbait17-validation-170630 into two datasets which one of them was used for testing.

**Comment by omidvaramin** [comment]
> 
> 
> The screenshot in the readme shows the `clickbait17-test` and `clickbait17-validation` directories next to `clickbait17-train-170331` and `clickbait17-validation-170630`. I get the latter two directories when unzipping the Clickbait Challange [dataset files](https://www.clickbait-challenge.org/#data). But where do the first two directories come from please?

As it is mentioned in the paper, since the real test data set has not yet been released, I split clickbait17-validation-170630 into two datasets which one of them was used for testing.

**Comment by potthast** [comment]
None. The test data are entirely separate from the training / validation data.

**Comment by artmatsak** [comment]
@potthast No intention to get the real test data for the competition here. I'm just trying to understand how the model was trained on the publicly available data during the hyperparameter tuning phase.

@omidvaramin Thank you for the explanation, it's now clear where `clickbait17-test` comes from. What about `clickbait17-validation` please? The paper doesn't seem to mention it, and from the code it's clear that the model is trained using a union of `clickbait17-validation` and `clickbait17-train-170331`.

**Comment by artmatsak** [comment]
Is `clickbait17-validation` the other 70% from `clickbait17-validation-170630` perhaps?

**Comment by omidvaramin** [comment]
> 
> 
> @potthast No intention to get the real test data for the competition here. I'm just trying to understand how the model was trained on the publicly available data during the hyperparameter tuning phase.
> 
> @omidvaramin Thank you for the explanation, it's now clear where `clickbait17-test` comes from. What about `clickbait17-validation` please? The paper doesn't seem to mention it, and from the code it's clear that the model is trained using a union of `clickbait17-validation` and `clickbait17-train-170331`.



> 
> 
> Is `clickbait17-validation` the other 70% from `clickbait17-validation-170630` perhaps?

**Comment by omidvaramin** [comment]
You are welcome,
Yes, I split clickbait17-validation-170630 into test (30 percent) and validation (70 percent).
